'use strict';
const assert=require('node:assert/strict');
const {Game,TYPES,stats,sum}=require('./game.js');
function run(g,seconds){for(let n=0;n<seconds*20;n++)g.tick(.05);}
function rich(){const g=new Game();g.gold=100000;g.materials=1000;return g;}
function assigned(g,type,x,y,count=1){const b=g.addBuilding(type,x,y);for(let i=0;i<count;i++){let w=g.workers.find(w=>!w.assigned);if(!w){g.hire(true);w=g.workers.at(-1);}w.assigned=b.id;const p=g.spots(b)[0];w.x=p.x;w.y=p.y;}return b;}
function stock(g,b,key){return (b.output[key]||0)+g.workers.reduce((n,w)=>n+(w.task?.source===b.id&&w.task.key===key&&w.task.phase==='delivery'?w.task.amount:0),0);}
function test(name,fn){fn();console.log('PASS '+name);}
test('all levels fit complete recipe batches',()=>{for(const type of Object.keys(TYPES)){if(['home','market','pile'].includes(type))continue;for(let level=1;level<=5;level++){const s=stats({type,level});for(const r of s.recipes){assert(s.input>=r.amount);assert(s.output>=sum(r.out));}}}});
test('workshop accepts mixed wood and stone and makes digital materials',()=>{const g=rich(),b=assigned(g,'workshop',3,3);b.input={wood:1,stone:1};const before=g.materials;run(g,8.1);assert.equal(g.materials,before+1);assert.equal(sum(b.output),0);assert.equal(sum(b.input),0);});
test('idle worker auto-assigns to an unstaffed building',()=>{const g=rich(),b=g.addBuilding('wood',3,3);run(g,.1);assert.equal(g.workers.filter(w=>w.assigned===b.id).length,1);});
test('absent worker pauses production',()=>{const g=rich(),b=assigned(g,'wood',3,3);g.startBatch(b);const w=g.workers.find(w=>w.assigned===b.id);w.x=10;w.y=10;run(g,.1);assert.equal(b.progress,0);});
test('multiple workers never multiply production',()=>{const g=rich(),b=assigned(g,'wood',3,3,2);run(g,8.1);const carried=g.workers.reduce((n,w)=>n+(w.task?.source===b.id&&w.task.phase==='delivery'?w.task.amount:0),0);assert.equal(sum(b.output)+carried,2);assert(g.workers.filter(w=>w.producing&&w.assigned===b.id).length<=1);});
test('both endpoints reserve inventory and capacity',()=>{const g=rich(),src=g.addBuilding('wood',3,3),dest=assigned(g,'workshop',8,3);src.output.wood=5;const a=g.workers.find(w=>w.assigned===dest.id),b=g.workers.find(w=>!w.assigned);assert(g.createTask(a,src,dest,'wood'));assert.equal(g.available(src,'wood'),0);assert.equal(g.incoming(dest),5);assert.equal(g.createTask(b,src,dest,'wood'),false);});
test('market does not take goods accepted by staffed downstream',()=>{const g=rich(),src=g.addBuilding('wood',3,3),dest=assigned(g,'workshop',8,3),market=g.buildings.find(b=>b.type==='market');g.workers.find(w=>!w.assigned).assigned=market.id;src.output.wood=5;const w=g.workers.find(w=>w.assigned===market.id);assert.equal(g.dispatch(w,src,true),false);dest.input.wood=stats(dest).input;assert.equal(g.dispatch(w,src,true),true);});
test('unstaffed downstream is ignored by sales',()=>{const g=rich(),src=g.addBuilding('wood',3,3);g.addBuilding('workshop',8,3);src.output.wood=5;assert(g.dispatch(g.workers[0],src,true));assert.equal(g.building(g.workers[0].task.dest).type,'market');});
test('automatic delivery produces materials without negatives',()=>{const g=rich(),src=assigned(g,'wood',3,3),dest=assigned(g,'workshop',8,3);run(g,100);assert(g.materials>1000);for(const b of [src,dest]){assert(Object.values(b.input).every(n=>n>=0));assert(Object.values(b.output).every(n=>n>=0));assert(sum(b.input)+g.incoming(b)<=stats(b).input);assert(sum(b.output)<=stats(b).output);}});
test('upgrading preserves active recipe until completion',()=>{const g=rich(),b=assigned(g,'chicken',3,3);b.input.grain=3;g.startBatch(b);assert(g.upgrade(b));assert.equal(b.batch.out.egg,1);run(g,10.1);assert.equal(b.output.egg,1);assert.equal(b.batch.out.egg,2);});
test('automatic egg recipes do not mix incompatible inputs',()=>{const g=rich(),b=assigned(g,'pickle',3,3);b.input={egg:1,duckegg:1};assert.equal(g.recipe(b),null);b.input.egg=2;run(g,10.1);assert.equal(stock(g,b,'century'),1);assert.equal(stock(g,b,'salted'),0);});
test('textile and dye recipes alternate automatically',()=>{const g=rich(),b=assigned(g,'textile',3,3);b.input={feather:2,fur:2};run(g,20.1);assert.equal(stock(g,b,'down'),1);assert.equal(stock(g,b,'plush'),1);const dye=assigned(g,'dye',8,3);dye.input={down:2,plush:2};run(g,24.1);assert.equal(stock(g,dye,'coat'),2);});
test('rent, grace and land ownership settle once',()=>{const g=new Game();g.gold=0;g.rentTime=.05;g.rent=50;run(g,.1);assert(g.grace>0);g.gold=100;run(g,.1);assert.equal(g.round,2);assert.equal(g.grace,null);g.gold=g.landPrice;assert(g.buyLand());assert.equal(g.buyLand(),false);const r=g.round;run(g,200);assert.equal(g.round,r);});
test('rent interval is one minute after every payment',()=>{const g=new Game();g.gold=1000;g.rentTime=.01;run(g,.1);assert.equal(g.round,2);assert(Math.abs(g.rentTime-59.95)<.001);});
test('failed rent stops the economy',()=>{const g=new Game();g.gold=0;g.rentTime=.05;g.rent=1000;run(g,31);assert(g.failed);const before=g.gold;run(g,2);assert.equal(g.gold,before);});
test('state serializes and resumes with transport reservations',()=>{const g=rich(),src=g.addBuilding('wood',3,3),dest=assigned(g,'workshop',8,3);src.output.wood=5;g.createTask(g.workers[0],src,dest,'wood');const resumed=new Game(g.serialize());assert.equal(resumed.available(resumed.building(src.id),'wood'),0);assert.equal(resumed.incoming(resumed.building(dest.id)),5);run(resumed,30);assert(resumed.materials>1000);});
test('building invalidates routes and does not isolate assigned workers',()=>{const g=rich(),b=assigned(g,'wood',3,3);const route=g.workers[0].route=[{x:4,y:4}];assert(g.build('farm',8,8));assert.notEqual(g.workers[0].route,route);g.workers[0].route=[{x:4,y:4}];assert.equal(g.canPlace('stone',4,4),false);});
console.log('All simulation checks passed.');
