'use strict';
const assert=require('node:assert/strict');
const {Game,TYPES,stats,sum}=require('./game.js');
function run(g,seconds){for(let n=0;n<seconds*20;n++)g.tick(.05);}
function rich(){const g=new Game();g.gold=100000;g.materials=1000;return g;}
function assigned(g,type,x,y,count=1){const b=g.addBuilding(type,x,y);for(let i=0;i<count;i++){let w=g.workers.find(w=>!w.assigned);if(!w){g.hire(true);w=g.workers.at(-1);}w.assigned=b.id;const p=g.workSpot(b);w.x=p.x;w.y=p.y;}return b;}
function stock(g,b,key){return (b.output[key]||0)+g.workers.reduce((n,w)=>n+((w.task?.source===b.id&&w.task.phase==='delivery'&&w.task.items)?(w.task.items[key]||0):0),0);}
function test(name,fn){fn();console.log('PASS '+name);}
test('all levels fit complete recipe batches',()=>{for(const type of Object.keys(TYPES)){if(['home','market','pile'].includes(type))continue;for(let level=1;level<=5;level++){const s=stats({type,level});for(const r of s.recipes){assert(s.input>=r.amount);assert(s.output>=sum(r.out));}}}});
test('workshop accepts mixed wood and stone and makes digital materials',()=>{const g=rich(),b=assigned(g,'workshop',3,3);b.input={wood:1,stone:1};const before=g.materials;run(g,8.1);assert.equal(g.materials,before+1);assert.equal(sum(b.output),0);assert.equal(sum(b.input),0);});
test('new construction assigns once and ticks preserve manual unassignment',()=>{const g=rich(),b=g.build('wood',3,3);assert.equal(g.workers.filter(w=>w.assigned===b.id).length,1);g.assign(b,-1);run(g,2);assert.equal(g.active(b),false);});
test('hiring fills empty buildings but does not add to staffed buildings',()=>{const g=rich(),b=g.addBuilding('wood',3,3);g.hire();assert(g.active(b));const n=g.workers.filter(w=>w.assigned===b.id).length;g.hire();assert.equal(g.workers.filter(w=>w.assigned===b.id).length,n);});
test('manual distribution averages idle villagers across empty buildings',()=>{const g=rich();for(let i=0;i<3;i++)g.hire(true);const a=g.addBuilding('wood',3,3),b=g.addBuilding('stone',8,3);assert.equal(g.autoAssign(true),5);assert.equal(g.workers.filter(w=>w.assigned===a.id).length,3);assert.equal(g.workers.filter(w=>w.assigned===b.id).length,2);});
test('home pays exactly once each second and survives saving mid-second',()=>{const g=new Game(),gold=g.gold,rate=stats(g.buildings.find(b=>b.type==='home')).income;run(g,.5);assert.equal(g.gold,gold);const resumed=new Game(g.serialize());run(resumed,.5);assert.equal(resumed.gold,gold+rate);run(resumed,9);assert.equal(resumed.gold,gold+rate*10);assert.equal(resumed.feedback.length,10);assert(!('feedback' in resumed.serialize()));});
test('worker upgrades cost resources independently and apply globally',()=>{const g=rich();assert(g.upgradeWorkers('carryLevel'));assert.equal(g.carryLevel,2);assert.equal(g.speedLevel,1);assert.equal(g.gold,99940);assert.equal(g.materials,994);assert(g.upgradeWorkers('speedLevel'));assert.equal(g.speedLevel,2);});
test('absent worker pauses production',()=>{const g=rich(),b=assigned(g,'wood',3,3);g.startBatch(b);const w=g.workers.find(w=>w.assigned===b.id);w.x=10;w.y=10;run(g,.1);assert.equal(b.progress,0);});
test('multiple workers never multiply production',()=>{const g=rich(),b=assigned(g,'wood',3,3,2);run(g,8.1);const carried=g.workers.reduce((n,w)=>n+((w.task?.source===b.id&&w.task.phase==='delivery')?sum(w.task.items):0),0);assert.equal(sum(b.output)+carried,1);assert(g.workers.filter(w=>w.producing&&w.assigned===b.id).length<=1);});
test('both endpoints reserve inventory and capacity',()=>{const g=rich(),src=g.addBuilding('wood',3,3),dest=assigned(g,'workshop',8,3);src.output.wood=5;const a=g.workers.find(w=>w.assigned===dest.id),b=g.workers.find(w=>!w.assigned);const cap=stats(dest).input;assert(g.createTask(a,src,dest,'wood'));assert.equal(g.available(src,'wood'),5-cap);assert.equal(g.incoming(dest),cap);assert.equal(g.createTask(b,src,dest,'wood'),false);});
test('market does not take goods accepted by staffed downstream',()=>{const g=rich(),src=g.addBuilding('wood',3,3),dest=assigned(g,'workshop',8,3),market=g.buildings.find(b=>b.type==='market');g.workers.find(w=>!w.assigned).assigned=market.id;src.output.wood=stats(src).output;const w=g.workers.find(w=>w.assigned===market.id);assert.equal(g.dispatch(w,src,true),false);dest.input.wood=stats(dest).input;assert.equal(g.dispatch(w,src,true),true);});
test('unstaffed downstream is ignored by sales once full',()=>{const g=rich(),src=g.addBuilding('wood',3,3);g.addBuilding('workshop',8,3);src.output.wood=stats(src).output;assert(g.dispatch(g.workers[0],src,true));assert.equal(g.building(g.workers[0].task.dest).type,'market');});
test('building worker sells only when output is full, market worker sells any stock',()=>{const g=rich(),src=g.addBuilding('wood',3,3);src.output.wood=stats(src).output-1;assert.equal(g.takeOutput(g.workers[0],src),false);src.output.wood=stats(src).output;assert(g.takeOutput(g.workers[0],src));src.output.wood=1;assert(g.dispatch(g.workers[0],src,true));});
test('automatic delivery produces materials without negatives',()=>{const g=rich(),src=assigned(g,'wood',3,3),dest=assigned(g,'workshop',8,3);run(g,100);assert(g.materials>1000);for(const b of [src,dest]){assert(Object.values(b.input).every(n=>n>=0));assert(Object.values(b.output).every(n=>n>=0));assert(sum(b.input)+g.incoming(b)<=stats(b).input);assert(sum(b.output)<=stats(b).output);}});
test('upgrading preserves active recipe and applies 1-3 random mods',()=>{const g=rich(),b=assigned(g,'chicken',3,3);b.input.grain=3;g.startBatch(b);const before=b.batch.out.egg;assert(g.upgrade(b));assert.equal(b.batch.out.egg,before);const applied=Object.values(b.mods||{}).reduce((a,c)=>a+c,0);assert(applied>=1&&applied<=3);run(g,20);assert(Object.keys(b.mods).length>=1);});
test('automatic egg recipes do not mix incompatible inputs',()=>{const g=rich(),b=assigned(g,'pickle',3,3);b.input={egg:2};run(g,10.1);assert.equal(stock(g,b,'century'),1);assert.equal(stock(g,b,'salted'),0);});
test('textile and dye recipes alternate automatically',()=>{const g=rich(),b=assigned(g,'textile',3,3);b.input={feather:2,fur:2};run(g,20.1);assert.equal(stock(g,b,'down'),1);assert.equal(stock(g,b,'plush'),1);const dye=assigned(g,'dye',8,3);dye.input={down:2,plush:2};run(g,24.1);assert.equal(stock(g,dye,'coat'),2);});
test('rent, grace and land ownership settle once',()=>{const g=new Game();g.gold=0;g.rentTime=.05;g.rent=50;run(g,.1);assert(g.grace>0);g.gold=100;run(g,.1);assert.equal(g.round,2);assert.equal(g.grace,null);g.gold=g.landPrice;assert(g.buyLand());assert.equal(g.buyLand(),false);const r=g.round;run(g,200);assert.equal(g.round,r);});
test('rent interval resets to configured length after every payment',()=>{const g=new Game();g.gold=1000;g.rentTime=.01;run(g,.1);assert.equal(g.round,2);assert(Math.abs(g.rentTime-(g.rentInterval-.05))<.01);});
test('failed rent stops the economy',()=>{const g=new Game();g.gold=0;g.rentTime=.05;g.rent=1000;run(g,31);assert(g.failed);const before=g.gold;run(g,2);assert.equal(g.gold,before);});
test('state serializes and resumes with transport reservations',()=>{const g=rich(),src=g.addBuilding('wood',3,3),dest=assigned(g,'workshop',8,3);src.output.wood=5;const cap=stats(dest).input;g.createTask(g.workers[0],src,dest,'wood');const resumed=new Game(g.serialize());assert.equal(resumed.available(resumed.building(src.id),'wood'),5-cap);assert.equal(resumed.incoming(resumed.building(dest.id)),cap);run(resumed,80);assert(resumed.materials>1000);});
test('building invalidates routes and does not isolate assigned workers',()=>{const g=rich(),b=assigned(g,'wood',3,3);const route=g.workers[0].route=[{x:4,y:4}];assert(g.build('farm',8,8));assert.notEqual(g.workers[0].route,route);g.workers[0].route=[{x:4,y:4}];assert.equal(g.canPlace('stone',4,4),false);});
test('output prefers an idle on-site worker then stays in output',()=>{const g=rich(),b=assigned(g,'wood',3,3,2);run(g,8.1);const carried=g.workers.filter(w=>w.assigned===b.id).reduce((n,w)=>n+((w.task?.phase==='delivery'&&w.task.source===b.id)?sum(w.task.items):0),0);assert.equal(carried+sum(b.output),1);assert(g.events.some(e=>e.type==='pickup'||e.type==='produceOut'));});
test('villagers can carry multiple material types in one trip',()=>{const g=rich(),src=assigned(g,'wood',3,3,1);src.output.wood=3;src.output.stone=3;const w=g.workers.find(x=>x.assigned===src.id);assert(w&&g.takeOutput(w,src));assert(sum(w.task.items)>1);assert(Object.keys(w.task.items).length>=1);});
test('overflow beyond input cap is sold at market',()=>{const g=rich(),src=g.addBuilding('wood',3,3),dest=assigned(g,'workshop',8,3);g.carryLevel=4;src.output.wood=10;const extra=g.workers.find(w=>!w.assigned)||(g.hire(true),g.workers.at(-1));const p=g.workSpot(src);extra.x=p.x;extra.y=p.y;extra.assigned=src.id;const w=g.workers.find(w=>w.assigned===src.id&&!w.task);assert(g.takeOutput(w,src));assert(w.task.dest===dest.id);assert(sum(w.task.items)>sum(w.task.reserved));run(g,80);assert(dest.input.wood<=stats(dest).input);assert(g.events.some(e=>e.type==='sell'&&e.items&&e.items.wood));});
test('simulation emits production, consumption and transport events',()=>{const g=rich(),src=assigned(g,'wood',3,3,2),dest=assigned(g,'workshop',8,3,1);run(g,120);for(const t of ['consume','pickup','deliver'])assert(g.events.some(e=>e.type===t),'missing '+t);});
console.log('All simulation checks passed.');
