'use strict';
const assert = require('node:assert/strict');
const { chromium } = require('playwright');
const { createServer } = require('../server');

(async () => {
  const service = createServer();
  await new Promise(resolve => service.server.listen(0, '127.0.0.1', resolve));
  const address = `http://127.0.0.1:${service.server.address().port}`;
  const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe', headless: true });
  try {
    const phone = { viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 2 };
    const hostContext = await browser.newContext(phone);
    const guestContext = await browser.newContext(phone);
    const host = await hostContext.newPage(), guest = await guestContext.newPage(), errors = [];
    host.on('pageerror', error => errors.push('host: ' + error.message));
    guest.on('pageerror', error => errors.push('guest: ' + error.message));
    await Promise.all([host.goto(address), guest.goto(address)]);
    await Promise.all([host.waitForFunction(() => !!window.Gufang), guest.waitForFunction(() => !!window.Gufang)]);
    await host.locator('#start-coop').click();
    await host.locator('#lan-controls summary').click();
    await host.locator('#server-toggle').click();
    await host.locator('#lan-create').click();
    await host.waitForFunction(() => /^\d{6}$/.test(Gufang.online?.code || ''));
    const code = await host.evaluate(() => Gufang.online.code);
    await guest.locator('#start-coop').click();
    await guest.locator('#lan-controls summary').click();
    await guest.locator('#server-toggle').click();
    await guest.locator('#lan-code').fill(code);
    await guest.locator('#lan-join').click();
    await host.waitForFunction(() => Gufang.online?.peerConnected);
    assert(await host.locator('#coop-start').isEnabled());
    await host.locator('#coop-start').click();
    await guest.waitForFunction(() => Gufang.state.mode === 'coop' && Gufang.online?.role === 'guest');
    const hostMap = await host.evaluate(() => ({ seed: Gufang.state.mapSeed, width: GF.worldWidth(Gufang.state), height: GF.worldHeight(Gufang.state) }));
    const guestMap = await guest.evaluate(() => ({ seed: Gufang.state.mapSeed, width: GF.worldWidth(Gufang.state), height: GF.worldHeight(Gufang.state) }));
    assert.deepEqual(guestMap, hostMap);
    const target = await guest.evaluate(() => {
      const s = Gufang.state, mine = GF.playerView(s, 1);
      for (let y = 0; y < GF.worldHeight(s); y++) for (let x = 0; x < GF.worldWidth(s); x++)
        for (const type of ['tea', 'tower', 'mulberry', 'quarry']) if (!GF.buildReason(mine, type, x, y)) return { x, y, type };
      return null;
    });
    assert(target, 'Guest estate has a buildable tile');
    await guest.evaluate(({ x, y }) => Gufang.select(x, y), target);
    await guest.locator(`[data-build="${target.type}"]`).click();
    await host.waitForFunction(({ x, y }) => Gufang.state.buildings.some(b => b.owner === 1 && b.x === x && b.y === y), target);
    await guest.waitForFunction(({ x, y }) => Gufang.state.buildings.some(b => b.owner === 1 && b.x === x && b.y === y), target);
    await host.evaluate(({ x, y }) => Gufang.select(x, y), target);
    assert(await host.locator('#panel').isHidden(), 'Host cannot edit the guest estate');
    const guestFunds = await guest.evaluate(() => [Gufang.state.partner.coins, Gufang.state.partner.materials]);
    const hostFunds = await host.evaluate(() => [Gufang.state.partner.coins, Gufang.state.partner.materials]);
    assert.deepEqual(guestFunds, hostFunds);
    await host.evaluate(() => {
      const s = Gufang.state;
      s.partner.coins = 10000; s.partner.materials = 10000;
      s.buildings.find(b => b.owner === 1 && b.type === 'shrine').level = 2;
    });
    await guest.waitForFunction(() => Gufang.state.partner.coins === 10000 && Gufang.state.buildings.some(b => b.owner === 1 && b.type === 'shrine' && b.level === 2));
    await guest.evaluate(({ x, y }) => Gufang.select(x, y), target);
    await guest.locator('#upgrade-building').click();
    await host.waitForFunction(({ x, y }) => Gufang.state.buildings.some(b => b.owner === 1 && b.x === x && b.y === y && b.level === 2), target);
    await guest.locator('#demolish-building').click();
    await guest.locator('[data-modal="confirm-demolish"]').click();
    await host.waitForFunction(({ x, y }) => !Gufang.state.buildings.some(b => b.owner === 1 && b.x === x && b.y === y), target);
    await host.locator('#menu-pause').click();
    const elapsed = await host.evaluate(() => Gufang.state.elapsed);
    await host.waitForTimeout(350);
    assert.equal(await host.evaluate(() => Gufang.state.elapsed), elapsed);
    await host.evaluate(() => { while (Gufang.state.phase !== 'night') GF.step(Gufang.state, .25); Gufang.refresh(); });
    await guest.waitForFunction(() => Gufang.state.phase === 'night');
    await guest.locator('[data-skill="repel"]').click();
    await host.waitForFunction(() => Gufang.state.partner.cooldowns.repel > 0);
    await host.locator('[data-modal="close"]').click();
    await guest.reload();
    await host.waitForFunction(() => Gufang.online && !Gufang.online.peerConnected);
    await guest.locator('#start-coop').click();
    await guest.locator('#lan-controls summary').click();
    await guest.locator('#server-toggle').click();
    await guest.locator('#lan-code').fill(code);
    await guest.locator('#lan-join').click();
    await guest.waitForFunction(() => Gufang.state.mode === 'coop' && Gufang.online?.peerConnected);
    assert(await host.evaluate(() => Gufang.online.peerConnected));
    await host.locator('#menu-pause').click();
    await host.locator('[data-modal="reset"]').click();
    await host.locator('[data-modal="new"]').click();
    const newSeed = await host.evaluate(() => Gufang.state.mapSeed);
    await guest.waitForFunction(seed => Gufang.state.mapSeed === seed && Gufang.state.day === 1, newSeed);
    await host.locator('#menu-pause').click();
    await host.locator('[data-modal="title"]').click();
    await guest.waitForFunction(() => !Gufang.online && !document.getElementById('start-menu').hidden);
    assert.deepEqual(errors, []);
    console.log('PASS LAN browser: room, two devices, guest build/upgrade/demolish/skill, ownership, state sync, pause, reconnect, restart, host departure');
  } finally {
    await browser.close();
    await service.close();
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
